
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EMPRESA = new javax.swing.JDialog();
        NOMBRE = new javax.swing.JLabel();
        id_empre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Arbol_empresas = new javax.swing.JTree();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_empleados = new javax.swing.JList<>();
        logout = new javax.swing.JButton();
        crear_empleado = new javax.swing.JButton();
        crea_empresa = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombre_empresa = new javax.swing.JTextField();
        fecha_empresa = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ubicacion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        id_empresa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pin_empresa = new javax.swing.JTextField();
        cb_empre = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        crea_empresas = new javax.swing.JButton();
        crea_emplea = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        emplenom = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        empledate = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        emplecorrep = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        empletipo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        emplecargo = new javax.swing.JTextField();
        creaemple = new javax.swing.JButton();
        cliclista = new javax.swing.JPopupMenu();
        verdeta = new javax.swing.JMenuItem();
        modificar = new javax.swing.JMenuItem();
        contratar = new javax.swing.JMenuItem();
        modifi = new javax.swing.JDialog();
        modifec = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        modico = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        modiemple = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        modicargo = new javax.swing.JTextField();
        modinom = new javax.swing.JTextField();
        modi_emple = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_empre_main = new javax.swing.JTextField();
        entrar_main = new javax.swing.JButton();
        Crea_empresa_main = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pin_empre_main = new javax.swing.JPasswordField();

        NOMBRE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NOMBRE.setText("jLabel4");

        id_empre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        id_empre.setText("jLabel4");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("empresa");
        Arbol_empresas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(Arbol_empresas);

        jLabel4.setText("lista de empleados");

        lista_empleados.setModel(new DefaultListModel());
        lista_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_empleadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lista_empleados);

        logout.setText("LogOut");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        crear_empleado.setText("Crear Empleado");
        crear_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crear_empleadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EMPRESALayout = new javax.swing.GroupLayout(EMPRESA.getContentPane());
        EMPRESA.getContentPane().setLayout(EMPRESALayout);
        EMPRESALayout.setHorizontalGroup(
            EMPRESALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EMPRESALayout.createSequentialGroup()
                .addGroup(EMPRESALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EMPRESALayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(id_empre, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EMPRESALayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(EMPRESALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EMPRESALayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)
                                .addComponent(crear_empleado))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EMPRESALayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(186, 186, 186))
        );
        EMPRESALayout.setVerticalGroup(
            EMPRESALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EMPRESALayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(EMPRESALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(id_empre, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(NOMBRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(EMPRESALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EMPRESALayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EMPRESALayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(crear_empleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(logout)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel5.setText("CREAR EMPRESAS");

        jLabel6.setText("nombre");

        jLabel7.setText("Fecha");

        jLabel8.setText("ubicacion de sucursal");

        jLabel9.setText("ID");

        jLabel10.setText("PIN acceso");

        cb_empre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pequeña", "mediana", "grande" }));

        jLabel11.setText("tipo");

        crea_empresas.setText("CREAR EMPRESA");
        crea_empresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crea_empresasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout crea_empresaLayout = new javax.swing.GroupLayout(crea_empresa.getContentPane());
        crea_empresa.getContentPane().setLayout(crea_empresaLayout);
        crea_empresaLayout.setHorizontalGroup(
            crea_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crea_empresaLayout.createSequentialGroup()
                .addGroup(crea_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crea_empresaLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel5))
                    .addGroup(crea_empresaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(crea_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(33, 33, 33)
                        .addGroup(crea_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_empre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fecha_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(nombre_empresa)
                            .addComponent(ubicacion)
                            .addComponent(id_empresa)
                            .addComponent(pin_empresa))))
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crea_empresaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(crea_empresas)
                .addGap(56, 56, 56))
        );
        crea_empresaLayout.setVerticalGroup(
            crea_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crea_empresaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addGroup(crea_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nombre_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(crea_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(37, 37, 37)
                .addGroup(crea_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(crea_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(id_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(crea_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pin_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(crea_empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_empre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crea_empresas)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel12.setText("CREAR EMPLEADO");

        jLabel13.setText("NOMBRE");

        jLabel14.setText("Fecha nacimiento");

        jLabel15.setText("correo");

        jLabel16.setText("tipo de empleado");

        empletipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ingeniero", "medico", "estudiante", "licenciado", "maestro" }));

        jLabel17.setText("cargo");

        creaemple.setText("crear");
        creaemple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creaempleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout crea_empleaLayout = new javax.swing.GroupLayout(crea_emplea.getContentPane());
        crea_emplea.getContentPane().setLayout(crea_empleaLayout);
        crea_empleaLayout.setHorizontalGroup(
            crea_empleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crea_empleaLayout.createSequentialGroup()
                .addGroup(crea_empleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crea_empleaLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel12))
                    .addGroup(crea_empleaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(crea_empleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(59, 59, 59)
                        .addGroup(crea_empleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emplenom)
                            .addComponent(empledate, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(emplecorrep)
                            .addComponent(empletipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emplecargo)))
                    .addGroup(crea_empleaLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(creaemple)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        crea_empleaLayout.setVerticalGroup(
            crea_empleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crea_empleaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(27, 27, 27)
                .addGroup(crea_empleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(emplenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(crea_empleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(empledate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(crea_empleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(emplecorrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(crea_empleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(empletipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(crea_empleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(emplecargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(creaemple)
                .addGap(31, 31, 31))
        );

        verdeta.setText("ver detalles");
        verdeta.setToolTipText("");
        verdeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdetaActionPerformed(evt);
            }
        });
        cliclista.add(verdeta);

        modificar.setText("modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        cliclista.add(modificar);

        contratar.setText("contratar");
        contratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarActionPerformed(evt);
            }
        });
        cliclista.add(contratar);

        jLabel18.setText("correo");

        jLabel19.setText("tipo de empleado");

        modiemple.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ingeniero", "medico", "estudiante", "licenciado", "maestro" }));

        jLabel20.setText("cargo");

        jLabel21.setText("NOMBRE");

        modi_emple.setText("modificar");
        modi_emple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modi_empleMouseClicked(evt);
            }
        });

        jLabel22.setText("Fecha nacimiento");

        javax.swing.GroupLayout modifiLayout = new javax.swing.GroupLayout(modifi.getContentPane());
        modifi.getContentPane().setLayout(modifiLayout);
        modifiLayout.setHorizontalGroup(
            modifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifiLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(modifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifiLayout.createSequentialGroup()
                        .addGroup(modifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(59, 59, 59)
                        .addGroup(modifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modinom)
                            .addComponent(modifec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modico)
                            .addComponent(modiemple, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modicargo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(modifiLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(modi_emple)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        modifiLayout.setVerticalGroup(
            modifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifiLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(modifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(modinom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(modifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(modifec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(modifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(modico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(modifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(modiemple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(modifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(modicargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modi_emple)
                .addGap(66, 66, 66))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("id de la empresa");

        jLabel2.setText("PIN de Acceso");

        entrar_main.setText("entrar");
        entrar_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrar_mainMouseClicked(evt);
            }
        });

        Crea_empresa_main.setText("crear empresa");
        Crea_empresa_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Crea_empresa_mainMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("BIENVENIDO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id_empre_main)
                            .addComponent(pin_empre_main, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(entrar_main)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 215, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Crea_empresa_main)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(182, 182, 182))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_empre_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(Crea_empresa_main)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pin_empre_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(entrar_main)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        EMPRESA.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void entrar_mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrar_mainMouseClicked
        // TODO add your handling code here:
        int id = 0;
        try {
            id = Integer.valueOf(id_empre_main.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "no ingreso numeros");
        }
        String pin = pin_empre_main.getText();
        boolean entra = false;
        int sele = 0;
        for (int i = 0; i < empre.size(); i++) {
            if (id == empre.get(i).getId() && pin.equals(empre.get(i).getPIN())) {
                sele = i;
                entra = true;
                p = empre.get(i);
                NOMBRE.setText(empre.get(i).getNombre());
                id_empre.setText("ID " + empre.get(i).getId());
            }
        }
        DefaultTreeModel m = (DefaultTreeModel) Arbol_empresas.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodoempre;
        nodoempre = new DefaultMutableTreeNode(empre.get(sele));
        raiz.add(nodoempre);
        
        if (entra == true) {
            EMPRESA.setModal(true);
            EMPRESA.pack();
            EMPRESA.setVisible(true);
        }
        id_empre_main.setText("");
        pin_empre_main.setText("");
        if (entra == false) {
            JOptionPane.showMessageDialog(this, "algun dato que ingreso esta incrrecto o la empresa no existe");
        }
    }//GEN-LAST:event_entrar_mainMouseClicked

    private void Crea_empresa_mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Crea_empresa_mainMouseClicked
        crea_empresa.setModal(true);
        crea_empresa.pack();
        crea_empresa.setVisible(true);
    }//GEN-LAST:event_Crea_empresa_mainMouseClicked

    private void crear_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crear_empleadoMouseClicked
        crea_emplea.setModal(true);
        crea_emplea.pack();
        crea_emplea.setVisible(true);
    }//GEN-LAST:event_crear_empleadoMouseClicked

    private void crea_empresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crea_empresasMouseClicked
        String nom = nombre_empresa.getText();
        Date fecha = fecha_empresa.getDate();
        String tipo = (String) cb_empre.getSelectedItem();
        String ubica = this.ubicacion.getText();
        int id = 0;
        try {
            id = Integer.valueOf(id_empresa.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(crea_empresa, "ingreso mal el id");
        }
        String pin = pin_empresa.getText();
        String tipod = (String) cb_empre.getSelectedItem();
        
        try {
            empre.add(new Empresas(nom, tipo, pin, fecha, ubica, id, pin, emple));
        } catch (Exception e) {
        }
        JOptionPane.showMessageDialog(crea_empresa, "se creo de forma correcta");
        nombre_empresa.setText("");
        ubicacion.setText("");
        id_empresa.setText("");
        pin_empresa.setText("");
        crea_empresa.dispose();
    }//GEN-LAST:event_crea_empresasMouseClicked

    private void creaempleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creaempleMouseClicked
        String noom = emplenom.getText();
        Date fech = empledate.getDate();
        String corre = emplecorrep.getText();
        String cargo = emplecargo.getText();
        String decem = (String) cb_empre.getSelectedItem();
        String salar = "";
        if (decem.equals("ingeniero")) {
            salar = "22,000";
        } else if (decem.equals("medico")) {
            salar = "18,000";
        } else if (decem.equals("estudiante")) {
            salar = "7600";
        } else if (decem.equals("licenciado")) {
            salar = "12,000";
        } else if (decem.equals("maestro")) {
            salar = "2000";
        }
        
        emple.add(new empleados(noom, fech, corre, salar, decem, cargo));
        JOptionPane.showMessageDialog(crea_emplea, "se creo de froma correcta");
        emplecargo.setText("");
        emplecorrep.setText("");
        emplenom.setText("");
        cb_empre.setSelectedIndex(0);
        DefaultListModel modelo = (DefaultListModel) lista_empleados.getModel();
        modelo.addElement(new empleados(noom, fech, corre, salar, decem, cargo));
        lista_empleados.setModel(modelo);
        crea_emplea.dispose();
    }//GEN-LAST:event_creaempleMouseClicked

    private void lista_empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_empleadosMouseClicked
        // TODO add your handling code here:
        if (lista_empleados.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                cliclista.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }

    }//GEN-LAST:event_lista_empleadosMouseClicked

    private void verdetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdetaActionPerformed
        int pos = lista_empleados.getSelectedIndex();
        JOptionPane.showMessageDialog(EMPRESA, emple.get(pos).detalles());

    }//GEN-LAST:event_verdetaActionPerformed

    private void contratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarActionPerformed
        if (lista_empleados.getSelectedIndex() >= 0) {
            DefaultTreeModel modeloarb = (DefaultTreeModel) Arbol_empresas.getModel();
            DefaultMutableTreeNode raiz
                    = (DefaultMutableTreeNode) modeloarb.getRoot();
            DefaultListModel modeloLISTA = (DefaultListModel) lista_empleados.getModel();
            String salario, nombre, cargo;

            //nombre, String salario, String cargo
            cargo = ((empleados) modeloLISTA.get(lista_empleados.getSelectedIndex())).getCargo();
            nombre = ((empleados) modeloLISTA.get(lista_empleados.getSelectedIndex())).getNombre();
            salario = ((empleados) modeloLISTA.get(lista_empleados.getSelectedIndex())).getSalario();
            int cent = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new empleados(nombre, salario, cargo));
                ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                cent = 1;
            }
            modeloarb.reload();
        } else {
            JOptionPane.showMessageDialog(this, "no hay persona seleccionada");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_contratarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        modifi.setModal(true);
        modifi.pack();
        modifi.setVisible(true);
    }//GEN-LAST:event_modificarActionPerformed

    private void modi_empleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modi_empleMouseClicked
         DefaultListModel modelolista=(DefaultListModel)lista_empleados.getModel();
         ((empleados)modelolista.get(lista_empleados.getSelectedIndex())).setNombre(modinom.getText());
         ((empleados)modelolista.get(lista_empleados.getSelectedIndex())).setCargo(modicargo.getText());
         ((empleados)modelolista.get(lista_empleados.getSelectedIndex())).setDesempe((String)modiemple.getSelectedItem());
         ((empleados)modelolista.get(lista_empleados.getSelectedIndex())).setCorreo(modico.getText());
         if (modiemple.getSelectedItem().equals("ingeniero")) {
            ((empleados)modelolista.get(lista_empleados.getSelectedIndex())).setSalario("22000");
        }
         if (modiemple.getSelectedItem().equals("medico")) {
            ((empleados)modelolista.get(lista_empleados.getSelectedIndex())).setSalario("18000");
        }
         if (modiemple.getSelectedItem().equals("estudiante")) {
            ((empleados)modelolista.get(lista_empleados.getSelectedIndex())).setSalario("7600");
        }
         if (modiemple.getSelectedItem().equals("licenciado")) {
            ((empleados)modelolista.get(lista_empleados.getSelectedIndex())).setSalario("12000");
        }if (modiemple.getSelectedItem().equals("maestro")) {
            ((empleados)modelolista.get(lista_empleados.getSelectedIndex())).setSalario("2000");
        }
         
         
    }//GEN-LAST:event_modi_empleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree Arbol_empresas;
    private javax.swing.JButton Crea_empresa_main;
    private javax.swing.JDialog EMPRESA;
    private javax.swing.JLabel NOMBRE;
    private javax.swing.JComboBox<String> cb_empre;
    private javax.swing.JPopupMenu cliclista;
    private javax.swing.JMenuItem contratar;
    private javax.swing.JDialog crea_emplea;
    private javax.swing.JDialog crea_empresa;
    private javax.swing.JButton crea_empresas;
    private javax.swing.JButton creaemple;
    private javax.swing.JButton crear_empleado;
    private javax.swing.JTextField emplecargo;
    private javax.swing.JTextField emplecorrep;
    private com.toedter.calendar.JDateChooser empledate;
    private javax.swing.JTextField emplenom;
    private javax.swing.JComboBox<String> empletipo;
    private javax.swing.JButton entrar_main;
    private com.toedter.calendar.JDateChooser fecha_empresa;
    private javax.swing.JLabel id_empre;
    private javax.swing.JTextField id_empre_main;
    private javax.swing.JTextField id_empresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lista_empleados;
    private javax.swing.JButton logout;
    private javax.swing.JButton modi_emple;
    private javax.swing.JTextField modicargo;
    private javax.swing.JTextField modico;
    private javax.swing.JComboBox<String> modiemple;
    private com.toedter.calendar.JDateChooser modifec;
    private javax.swing.JDialog modifi;
    private javax.swing.JMenuItem modificar;
    private javax.swing.JTextField modinom;
    private javax.swing.JTextField nombre_empresa;
    private javax.swing.JPasswordField pin_empre_main;
    private javax.swing.JTextField pin_empresa;
    private javax.swing.JTextField ubicacion;
    private javax.swing.JMenuItem verdeta;
    // End of variables declaration//GEN-END:variables
    ArrayList<Empresas> empre = new ArrayList();
    ArrayList<empleados> emple = new ArrayList();
    Empresas p;
}
